In [5]:
import numpy as np
from tqdm import tqdm


In [6]:
def Multiplicar_Matrices(A,B):
    shape_A=np.shape(A)
    filas_A=shape_A[0]
    columnas_A=shape_A[1]
    shape_B=np.shape(B)
    filas_B=shape_A[0]
    columnas_B=shape_A[1]
    C=np.empty((filas_A,columnas_B))
    if(filas_A==columnas_B):
        for i in tqdm(range(filas_A)):
            for j in range(columnas_B):
                C_ij = 0
                for k in range(columnas_A):
                    C_ij += A[i][k]*B[k][j]
                C[i][j] = C_ij   
        return C
    else:
        print("No es posible múltiplicar las matrices dadas, el número de filas de A debe coincidir con el número de columnas de B")
        return None

In [7]:
A = np.array([[1, 0, 0], [5, 1, 0], [-2, 3, 1]])
B = np.array([[4, -2, 1], [0, 3, 7], [0, 0, 2]])
C=Multiplicar_Matrices(A,B)
print(f"Si\nA:\n{A}\nB:\n{B}\n Obtenemos que\n AB:\n{C}")

100%|███████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 750.99it/s]

Si
A:
[[ 1  0  0]
 [ 5  1  0]
 [-2  3  1]]
B:
[[ 4 -2  1]
 [ 0  3  7]
 [ 0  0  2]]
 Obtenemos que
 AB:
[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
